### ISSUE TITLE
Commodore 64 GEOS - 1531 mouse

### ISSUE THREAD

**Issue by celso** [EmberHeavyIndustries/HID2AMI#10]
Would it be possible to support the 1351 analog mouse on the C64/128?

https://www.c64-wiki.com/wiki/Mouse

https://en.wikipedia.org/wiki/Commodore_1351

**Comment by EmberHeavyIndustries** [comment]
Not with the current hardware, sorry. As the name implies, it is an analog device; hid2ami is fully digital.
