### ISSUE TITLE
Is USB mouse wheel support planned?

### ISSUE THREAD

**Issue by apolkosnik** [EmberHeavyIndustries/HID2AMI#2]
Hello, I'm wondering if the freewheel compatible mouse wheel support is feasible or planned. 
Thank you,
-A

**Comment by EmberHeavyIndustries** [comment]
Not at the moment, because it need multiplexing the wheel movement information through quadrature waveform data, which in turn leads to a loss in precision and smoothness, which I decide to be the main requisite of HID2AMI
