### ISSUE TITLE
Small 'direction lag' when changing mouse movement direction

### ISSUE THREAD

**Issue by Aardvark1982** [EmberHeavyIndustries/HID2AMI#6]
Just a minor imperfection in the mouse movement behavior, this is how it's demonstrated:

Slowly move the mouse pointer to either left, right, up, or down.
Stop
Slowly move the pointer in the opposite direction

Notice that the initial movement is the first direction rather than the second.

Actually SmallyMouse2 adapter had exactly same behavior which apparently has been fixed. Here is link for it's issue report: https://github.com/simoninns/SmallyMouse2/issues/10

**Comment by XR4x4** [comment]
I have just built two of these and this exact Problem still exists with latest firmware. (25/1/24)

**Comment by EmberHeavyIndustries** [comment]
Huh, I completely forgot about that issue until you reminded it to me now ..... sorry.
I'll check soon.

**Comment by EmberHeavyIndustries** [comment]
Update: fixed in next v304 coming soon !

**Comment by EmberHeavyIndustries** [comment]
:)
