### ISSUE TITLE
Detached Atari keyboard (MegaSTE/TT) doesn't like HID2AMI very much

### ISSUE THREAD

**Issue by mikrosk** [EmberHeavyIndustries/HID2AMI#8]
I have bought two devices (pre-programmed to Atari mode) in "HID2AMI - 8th batch" on amibay. So I believe I'm running a fairly recent hardware and software. They work well, they recognise all of my USB mice, cool.

However I have noticed one oddity: when connected to my MegaSTE's or TT's external keyboard (what is my primary use case as their DSUB9 ports are easily accessible) upon boot, the keyboard is totally messed up in the desktop (i.e. keys are interpreted wrongly, if at all). Mouse still works all right. 

The only fix to it is:
- disconnect the mouse
- disconnect the keyboard
- reconnect the keyboard
- reconnect the mouse

If I keep the mouse connected, it doesn't help. If I unplug just the mouse, it doesn't help. Also, when I reset the Atari, the problem is back. So it seems to be somehow related to IKBD reset or something like that.

I tested it also on my STE, there's no such issue. Also I tested it on both Mega STE (8 MHz) and TT (48 MHz) so it's not related to TOS or CPU speed.

If there's a way to help you out with debugging, please let me know.

**Comment by mikrosk** [comment]
I tested it on my Falcon today: same issue.

**Comment by EmberHeavyIndustries** [comment]
Uh, sorry I missed this one. Reading now...
Unfortunately I only own an STE from the Atari world, so i can't debug in deep.
Maybe it could be related to the wheelmouse protocol (for the Amiga), which need some esotic interaction with mouse port pins.

Would you please send me an email at EmberHeavyIndustries@gmail.com with your adapter codes, so I can set up a modified version with that protocol disabled ? (useless for Atari).
