### ISSUE TITLE
Which controllers of the STM32F1xx series are allowed to be used?

### ISSUE THREAD

**Issue by alex-nemo** [EmberHeavyIndustries/HID2AMI#9]
Which controllers of the STM32F1xx series are allowed to be used?
Is it permissible to use STM32F1xx controllers in the LQFP-64 package. For example: STM32F103RBT6 [LQFP-64], STM32F103RCT6 [LQFP-64], STM32F103RET6 [LQFP-64]. 
Can I remake the board for STM32F1xx in the LQFP-48 package.  For example: STM32F103C8T6 [LQFP-48], STM32F103CBT6 [LQFP-48].

**Comment by EmberHeavyIndustries** [comment]
You can pin-to-pin swap F105RBT6 or F105RCT6 (the latter doubles the flash internal memory)
You cal also swap with F205RXT6 (pointless because they are more expensive than F105)
You can't swap with F103, because they don't support USB HOST functionality which is needed
